package com.gabrielkaiki.appprevisao.api

import com.gabrielkaiki.appprevisao.R

//Chave de teste 89242f5f
//Chave para lançamento 453ac24a
var clima_api_key = "453ac24a"
var codigoCondicao: HashMap<Int, Any> = hashMapOf(
    0 to R.drawable.tempestades,
    1 to R.drawable.tempestades,
    2 to R.drawable.tornado,
    3 to R.drawable.tempestades,
    4 to R.drawable.tempestades,
    5 to R.drawable.sol_nuvem_neve,
    6 to R.drawable.gelo,
    7 to R.drawable.gelo,
    8 to R.drawable.neve,
    9 to R.drawable.chuva,
    10 to R.drawable.sol_nuvem_neve,
    11 to R.drawable.chuva,
    12 to R.drawable.chuva,
    13 to R.drawable.sol_nuvem_neve,
    14 to R.drawable.sol_nuvem_neve,
    15 to R.drawable.ventania_neve,
    16 to R.drawable.neve,
    17 to R.drawable.chuva_granizo,
    18 to R.drawable.gelo,
    19 to R.drawable.poeira,
    20 to R.drawable.neblina,
    21 to R.drawable.tempestade_de_areia,
    22 to R.drawable.fumaca,
    23 to R.drawable.vento,
    24 to R.drawable.vento,
    25 to R.drawable.tempo_frio,
    26 to R.drawable.nublado,
    27 to R.drawable.tempo_limpo,
    28 to R.drawable.nublado,
    29 to R.drawable.parcialmente_nublado,
    30 to R.drawable.parcialmente_nublado,
    31 to R.drawable.tempo_limpo,
    32 to R.drawable.ensolarado,
    33 to R.drawable.estrelado,
    34 to R.drawable.tempo_limpo,
    35 to R.drawable.chuva_granizo,
    36 to R.drawable.ar_quente,
    37 to R.drawable.tempestades,
    38 to R.drawable.tempestades,
    39 to R.drawable.tempestades,
    40 to R.drawable.chuva,
    41 to R.drawable.tempestades,
    42 to R.drawable.sol_nuvem_neve,
    43 to R.drawable.neve,
    44 to R.drawable.tempo_limpo,
    45 to R.drawable.chuva,
    46 to R.drawable.sol_nuvem_neve,
    47 to R.drawable.tempestades,
    48 to R.drawable.indisponivel
)

var codigoTraducao: HashMap<Int, Any> = hashMapOf(
    0 to "Strong storm",
    1 to "Tropical storm",
    2 to "Hurricane",
    3 to "Severe storms",
    4 to "Storms",
    5 to "Mixed snow and rain",
    6 to "Mixed rain and ice",
    7 to "Mixed snow and ice",
    8 to "Fine frost",
    9 to "Sprinkles",
    10 to "Freezing rain",
    11 to "Some sprinkles",
    12 to "Some sprinkles",
    13 to "Low snow",
    14 to "Snow storm",
    15 to "Gust of snow",
    16 to "Snow",
    17 to "Hail",
    18 to "Ice",
    19 to "Dust",
    20 to "Mist",
    21 to "Sand storm",
    22 to "Smoky",
    23 to "Sharp wind",
    24 to "Gale",
    25 to "Cold weather",
    26 to "Cloudy weather",
    27 to "Clear weather",
    28 to "Cloudy weather",
    29 to "Partly cloudy",
    30 to "Partly cloudy",
    31 to "Clear weather",
    32 to "Sunny",
    33 to "Starry",
    34 to "Sunny with lots of clouds",
    35 to "Mixed rain and hail",
    36 to "Hot air",
    37 to "Isolated storms",
    38 to "Scattered thunderstorms",
    39 to "Scattered thunderstorms",
    40 to "Sparse rains",
    41 to "Heavy snow",
    42 to "Drizzles with snow",
    43 to "Heavy snow",
    44 to "Sun with few clouds",
    45 to "Rain",
    46 to "Snow fall",
    47 to "Isolated storms",
    48 to "Service Unavailable"
)

var descricaoCondicao: HashMap<String, Any> = hashMapOf(
    "Tempestade forte" to R.drawable.tempestades,
    "Tempestade tropical" to R.drawable.tempestades,
    "Furacão" to R.drawable.tornado,
    "Tempestades severas" to R.drawable.tempestades,
    "Tempestades" to R.drawable.tempestades,
    "Misto de neve e chuva" to R.drawable.sol_nuvem_neve,
    "Misto chuva e gelo" to R.drawable.gelo,
    "Misto neve e gelo" to R.drawable.gelo,
    "Geada fina" to R.drawable.neve,
    "Chuviscos" to R.drawable.chuva,
    "Congelamento chuva" to R.drawable.sol_nuvem_neve,
    "Alguns chuviscos" to R.drawable.chuva,
    "Alguns chuviscos" to R.drawable.chuva,
    "Neve baixa" to R.drawable.sol_nuvem_neve,
    "Tempestade com neve" to R.drawable.sol_nuvem_neve,
    "Ventania com neve" to R.drawable.ventania_neve,
    "Neve" to R.drawable.neve,
    "Granizo" to R.drawable.chuva_granizo,
    "Gelo" to R.drawable.gelo,
    "Poeira" to R.drawable.poeira,
    "Neblina" to R.drawable.neblina,
    "Tempestade de areia" to R.drawable.tempestade_de_areia,
    "Fumacento" to R.drawable.fumaca,
    "Vento acentuado" to R.drawable.vento,
    "Ventania" to R.drawable.vento,
    "Tempo frio" to R.drawable.tempo_frio,
    "Tempo nublado" to R.drawable.nublado,
    "Tempo limpo" to R.drawable.tempo_limpo,
    "Tempo nublado" to R.drawable.nublado,
    "Parcialmente nublado" to R.drawable.parcialmente_nublado,
    "Parcialmente nublado" to R.drawable.parcialmente_nublado,
    "Tempo limpo" to R.drawable.tempo_limpo,
    "Ensolarado" to R.drawable.ensolarado,
    "Estrelado" to R.drawable.estrelado,
    "Ensolarado com muitas nuvens" to R.drawable.tempo_limpo,
    "Misto chuva e granizo" to R.drawable.chuva_granizo,
    "Ar quente" to R.drawable.ar_quente,
    "Tempestades isoladas" to R.drawable.tempestades,
    "Trovoadas dispersas" to R.drawable.tempestades,
    "Trovoadas dispersas" to R.drawable.tempestades,
    "Chuvas esparsas" to R.drawable.chuva,
    "Pesados neve" to R.drawable.neve,
    "Chuviscos com neve" to R.drawable.sol_nuvem_neve,
    "Neve pesada" to R.drawable.neve,
    "Sol com poucas nuvens" to R.drawable.tempo_limpo,
    "Chuva" to R.drawable.chuva,
    "Queda de neve" to R.drawable.sol_nuvem_neve,
    "Tempestade isoladas" to R.drawable.tempestades,
    "Serviço indisponível" to R.drawable.indisponivel
)